
# 定义工作流名称
name: deploy-website

# 设置 分支 在代码 push 后执行工作流
on:
  push:
    branches:
      - main
    paths:
      - BuildLog.md

# 需要执行的具体任务
jobs:
  build:
    name: build-website
    # 运行环境
    runs-on: ${{ matrix.os }}
    # 暂且理解为 变量
    strategy:
      matrix:
        node_version: ["16.X"]
        os: [ubuntu-latest]
    # 具体步骤
    steps:
      - uses: actions/checkout@v2
      
      # step 名称 - 1）安装和使用 Node
      - name: Use Node.js ${{ matrix.node_version }}
        # actions 包，可以理解为 node_modules 下的包
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node_version }}
          
      # step 名称 - 2）安装 node_modules
      - name: instal deps
        # 执行的命令
        run: npm install
        
      # step 名称 - 3）项目构建
      - name: build app
        run: npm run build
        
      # step 名称 - 4）将构建包 scp 到线上服务器
      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.1.4
        with:
          # 服务器 ip
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          # ssh 连接端口
          port: 22
          # 资源所在位置
          source: "dist/"
          # scp 到服务器的目标位置
          target: ${{ secrets.REMOTE_TARGET }}










      
